/**
 * Button — port of element/button.phtml.
 *
 * Fields: title, button_style, button_size, add_icon, icon (fontawesome class),
 * icon_position (left|right), link, display_as_link, onclick_code.
 *
 * Per-button color/border styling (button_color, button_background_color, hover,
 * gradient, 3d, full_width) is generated by ElementStyle::getButtonStyleHtml() on
 * the storefront. A faithful port of that lives in styleButton() below and is
 * emitted as a scoped <style>. Icon glyphs require a font (FontAwesome/Magezon
 * mgz-font) to be present in the host app — see README.
 */
import React from 'react';
import type { MagezonElement, MagezonElementProps } from '../types';
import { getLinkParams, linkAttrs } from '../links';
import { bool, str } from '../media';

function cssColor(v: unknown): string {
  const s = str(v);
  if (!s) return '';
  return !s.startsWith('#') && !s.startsWith('rgb') && s !== 'transparent' ? `#${s}` : s;
}
function cssProp(v: unknown): string {
  const s = str(v);
  if (!s) return '';
  return /^-?\d*\.?\d+$/.test(s) ? `${s}px` : s;
}

function styleButton(el: MagezonElement): string {
  const sel = `.mgz-element.${el.id} .mgz-link`;
  const normal: string[] = [];
  if (el.button_border_width !== undefined) {
    normal.push(`border-width:${cssProp(el.button_border_width)}`);
    if (el.button_border_style) normal.push(`border-style:${str(el.button_border_style)}`);
    if (el.button_border_color) normal.push(`border-color:${cssColor(el.button_border_color)}`);
  }
  if (el.button_border_radius !== undefined) normal.push(`border-radius:${cssProp(el.button_border_radius)}`);
  if (el.button_color) normal.push(`color:${cssColor(el.button_color)}`);
  if (el.button_background_color) normal.push(`background-color:${cssColor(el.button_background_color)}`);
  if (bool(el.full_width)) normal.push('width:100%');
  if (str(el.button_style) === 'gradient') {
    const c1 = cssColor(el.gradient_color_1);
    const c2 = cssColor(el.gradient_color_2);
    normal.push(`background-color:${c1}`);
    normal.push(`background-image:linear-gradient(to right, ${c1} 0%, ${c2} 50%, ${c1} 100%)`);
    normal.push('background-size:200% 100%');
  }
  if (str(el.button_style) === '3d' && el.box_shadow_color) {
    normal.push(`box-shadow:0 5px 0 ${cssColor(el.box_shadow_color)}`);
  }

  const hover: string[] = [];
  if (el.button_hover_color) hover.push(`color:${cssColor(el.button_hover_color)}`);
  if (el.button_hover_background_color) hover.push(`background-color:${cssColor(el.button_hover_background_color)}`);
  if (el.button_hover_border_color) hover.push(`border-color:${cssColor(el.button_hover_border_color)}`);

  let css = '';
  if (normal.length) css += `${sel}{${normal.join(';')};}`;
  if (hover.length) css += `${sel}:hover{${hover.join(';')};}`;
  return css;
}

export function Button({ element }: MagezonElementProps) {
  const title = str(element.title);
  const link = getLinkParams(element.link);
  const btnStyle = str(element.button_style);
  const btnSize = str(element.button_size);
  const displayAsLink = bool(element.display_as_link);
  const addIcon = bool(element.add_icon);
  const icon = str(element.icon);
  const iconPos = str(element.icon_position);
  const css = styleButton(element);

  return (
    <div className={`mgz-button mgz-btn-style-${btnStyle} mgz-btn-size-${btnSize}`}>
      <a
        href={link.url || '#'}
        className={`mgz-link ${!displayAsLink ? 'mgz-btn' : ''}`.trim()}
        title={link.title}
        {...linkAttrs(link)}
      >
        {addIcon && icon && iconPos === 'left' && <i className={icon} />}
        {title}
        {addIcon && icon && iconPos === 'right' && <i className={icon} />}
      </a>
      {css ? <style dangerouslySetInnerHTML={{ __html: css }} /> : null}
    </div>
  );
}
